spring.application.name=tag

spring.datasource.url=jdbc:mysql://localhost:3306/Muttley?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=@nder03Sql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=false
spring.mvc.hiddenmethod.filter.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.thymeleaf.cache=false
server.port=8092

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pedronoboru8@gmail.com
spring.mail.password=awriziowlbgoeyhf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

muttley.mail.remetente=Muttley - Gestao Academica <pedronoboru8@gmail.com>
